server:
  port: 8085
spring:
  application:
    name: CONFIG-PROD

  cloud:
    config:
      server:
        git:
          uri: https://github.com/bhanuchandrika99/microservices_config
          clone-on-start: true
